// Word Sprint (RF-04): decisión léxica. Palabras reales en español vs.
// pseudopalabras (secuencias con forma de palabra pero sin significado).
export const WORD_SPRINT_ITEMS: { word: string; isReal: boolean }[] = [
  { word: "MESA", isReal: true },
  { word: "LIBRO", isReal: true },
  { word: "CAFÉ", isReal: true },
  { word: "VENTANA", isReal: true },
  { word: "CAMINO", isReal: true },
  { word: "PUENTE", isReal: true },
  { word: "MONTAÑA", isReal: true },
  { word: "ESTRELLA", isReal: true },
  { word: "SILLA", isReal: true },
  { word: "JARDÍN", isReal: true },
  { word: "ESPEJO", isReal: true },
  { word: "RELOJ", isReal: true },
  { word: "PAPEL", isReal: true },
  { word: "NUBE", isReal: true },
  { word: "CIUDAD", isReal: true },
  { word: "TRALME", isReal: false },
  { word: "BONDECA", isReal: false },
  { word: "FILUSTRE", isReal: false },
  { word: "CANOPRA", isReal: false },
  { word: "DELUNTE", isReal: false },
  { word: "ESPADRO", isReal: false },
  { word: "MOLTIZA", isReal: false },
  { word: "PRENAJO", isReal: false },
  { word: "BRONTAL", isReal: false },
  { word: "FILECHO", isReal: false },
  { word: "CASPUNTE", isReal: false },
  { word: "MOLARDE", isReal: false },
  { word: "TRENIZO", isReal: false },
  { word: "GAVUNTE", isReal: false },
  { word: "PELONDRA", isReal: false },
];
